### ISSUE TITLE
Language Request

### ISSUE THREAD

**Issue by salman660** [sbeve72/JADA#2]
Hello, Can you plzz add the Urdu language and Additionally I really loved your project and want to contribute to it.
I can help you with the graphic assets bcoz I am a graphic designer and I you want your app to be published on the play store for free I can publish this app for no cost, trust me here is the link to my developer page: https://play.google.com/store/apps/dev?id=5781774584219069382

**Comment by sbeve72** [comment]
Hello,
Thank you for your interest in my project. It means a lot to me. Unfortunately, the Rest API the app uses does not support Urdu and even Arabic has some issues with it. I appreciate your offer to publish my app to the playstore, we can talk about it in detail over some sort of chat app, if you will. I also really appreciate your offer to contribute to my app, we can talk about it in detail in whatever messaging app we decide on.

**Comment by salman660** [comment]
thanks, Yusuf for replying to me. I am on Instagram and Facebook
Instagram: @salmanoyee
Facebook: facebook.com/salmanoyee.660/

It's on you which platform you prefer but I am more active on Instagram 😊
