### ISSUE TITLE
Br Portuguese doesn't work

### ISSUE THREAD

**Issue by GiovanniSalmeri** [sbeve72/JADA#3]
Installed from IzzyOnDroid, v. 4.4.0 All works flawlessly, except for Br Portuguese: when selected no definition is found (tried with several common protuguese words) and moreover the option for changing the language disappears (I was forced to reinstall). Thank you!

**Comment by sbeve72** [comment]
Hello, thank you for showing your interest in my app, that means a lot. 
>Installed from IzzyOnDroid, v. 4.4.0 All works flawlessly, except for Br Portuguese: when selected no definition is found (tried with several common protuguese words)

After doing some debugging I found out about [issue: 102](https://github.com/meetDeveloper/freeDictionaryAPI/issues/102). Apparently, this is part of the gradual migration to the new api and support for Portuguese may be dropped from the API. I will try to bring it back but I can't make any promises.
>the option for changing the language disappears (I was forced to reinstall). Thank you!

I have fixed the underlying reason but this will no longer be verifiable since I will also be removing support for the languages that don't work until I find a different api that supports more languages.

If you don't mind, I would like to know if you are a Portuguese speaker as that will help me understand if my users really use other languages.

**Comment by GiovanniSalmeri** [comment]
Thank you very much for taking the time for this issue. I have read https://github.com/meetDeveloper/freeDictionaryAPI/issues/102 : it would be really unfortunate if support for non-English languages were dropped from the API... I am not a Portuguese speaker (I am Italian), but quite often I read texts in other languages: your app is **extremely** useful for those who have a limited knowledge of a foreign language, because normally a dictionary entry explains a (unknown) word by means of more common (and known) words. Some minutes after me, also my wife (whose mother tongue is French) installed it!

**Comment by sbeve72** [comment]
I am planning to buy [this](https://developer.oxforddictionaries.com/?tag=#plans) and if I manage to afford it, I will update my app to use that api and close this issue. If you can help me with donations, feel free to reply, most of us developers are broke students in their teens (or at least so is the case for me).

**Comment by GiovanniSalmeri** [comment]
Will the definitions be so complete as now? Trying the box "Enter a word to test the API" at page https://developer.oxforddictionaries.com/ only the first definition presently shown in JADA appears. Anyway, I will gladly contribute if this helps you (and the app :smile:)

**Comment by sbeve72** [comment]
Which word did you look up? It may just be showing a truncated version
since it's just to test the api. Maybe if I can make a throwaway to check
if the definitions are as complete.

**Comment by GiovanniSalmeri** [comment]
I tried several words, for example "freedom": in JADA five meanings, there only the first.

**Comment by sbeve72** [comment]
Thanks for letting me know. I am testing this right now.

**Comment by sbeve72** [comment]
@GiovanniSalmeri Apparently, it works fine if you have an api key. This api seems more efficient to me if I manage to buy the developer package. For now I need to build the Pojos and other stuff.

**Comment by sbeve72** [comment]
Accidentally closed :p

**Comment by sbeve72** [comment]
Mitigated with commit 2308a4c51ec533c29f73b92101b9a06c713a97ec. 

JADA 5 supports different languages (Portuguese no longer on the list). Issues like word not found should no longer occur as often with JADA 5.
