### ISSUE TITLE
Question about support for other dictionaries

### ISSUE THREAD

**Issue by soratobukuroneko** [sbeve72/JADA#5]
Hello,

I just installed your application and quickly tested it. Seems to be pretty cool!

I admit I didn't investigate thoroughly by myself, but I have some questions. First, do you plan to implement support for other dictionaries? For instance wiktionary (supposing they have an API)? And could you give me some clue how such support could be added to your application (for a non-mobile dev)?

Thank you!

**Comment by sbeve72** [comment]
> I admit I didn't investigate thoroughly by myself, but I have some questions. First, do you plan to implement support for other dictionaries? For instance wiktionary (supposing they have an API)?

No such plans so far but if you can give me a good reason to support multiple dictionary APIs then I might do it.

>  And could you give me some clue how such support could be added to your application (for a non-mobile dev)?

You either use custom parsing of JSON to a model class or use some library for the language you're using (for example Java devs 
use GSON or Moshi and Kotlin devs usually prefer Moshi). Basically this is the cycle -:

* HTTP get request to the server with information about the word that the user has input in your dictionary app (such as the language and the word's text itself)
* The server returns a response in form of a Response object which contains the JSON body as a String. You convert that String to a your model class using one of the JSON parsing library.
* You use your object instance of the model class to show the data in the UI
